### ISSUE TITLE
colmt.lua中的find函数num_each_query 不起作用

### ISSUE THREAD

**Issue by stallion5632** [litingtingting/lua-resty-mongol3#1]
mongod版本3.6
数据库中满足条件的数据有10w条，num_each_query 设为1000条不起作用，仍然尝试返回10w条。
colmt.lua中的find函数num_each_query 不起作用
但，colmt.lua中的query函数可以使用。

能问下存在该问题吗？如何修改？

**Comment by litingtingting** [comment]
可以使用 cursor:limit(1000) 来限制条数，find方法依赖的是query函数。

**Comment by litingtingting** [comment]
可以使用 cursor:limit( n ) 来限制条数
